### ISSUE TITLE
*new to code* Create "status" menu button; to lead to "status" on front page.

### ISSUE THREAD

**Issue by RichardWild001** [ethereum/www#1]
Create "status" menu button; to lead to "status" on front page. As requested from meeting 06/05/14

**Comment by nickfierro** [comment]
Can not link a menu button to the status portion of the news section due to the plugin that it is being used. I recommend moving that part to its own section on the site.

**Comment by RichardWild001** [comment]
Try this?

http://liquidslider.com/documentation/

![screen shot 2014-05-22 at 09 35 16](https://cloud.githubusercontent.com/assets/6830638/3051415/0acbedc0-e18c-11e3-8546-2739e51cc491.png)

**Comment by nickfierro** [comment]
I will

**Comment by nickfierro** [comment]
Completed a week ago.
