### ISSUE TITLE
forum.ethereum.org "The certificate is not trusted because no issuer chain was provided."

### ISSUE THREAD

**Issue by nejucomo** [ethereum/www#35]
(_Note:_ I'm not sure this is the right place for forum issues; if not, let me know of a better site.)

On Debian, with Iceweasel (a Firefox fork), I get this error when visiting https://forum.ethereum.org:

```
The certificate is not trusted because no issuer chain was provided.
```

This mozilla support site suggests that my system is missing an intermediate certificate:
- https://support.mozilla.org/en-US/questions/1003783

I verified this with ssllabs:
- https://www.ssllabs.com/ssltest/analyze.html?d=forum.ethereum.org

**Comment by tgerring** [comment]
Hello and thanks for the report! We'll be generating and replacing our forum certificate soon and intend to improve a few issues highlighted in the SSL labs report. Since this isn't directly related to the www.etheruem.org website, I'm closing this issue for now.
