### ISSUE TITLE
bad links 

### ISSUE THREAD

**Issue by awrelll** [ethereum/www#36]
-Pokereum points to https://http//www.pokereum.io
-ethergit seems to be down for some time.
-cubespawn points to a subdomain than no longer exists https://main.cubespawn.com/cgi-sys/defaultwebpage.cgi

**Comment by tgerring** [comment]
I think this belongs at ethereum/ethereum.org

**Comment by awrelll** [comment]
it might be a private repo beceause i can't see it. where should i post this issue ?

**Comment by tgerring** [comment]
@awrelll The new repo should be public now
