### ISSUE TITLE
Header can grow too large

### ISSUE THREAD

**Issue by tgerring** [ethereum/www#7]
The header "movie" area appears to be proportional to the webpage window size. On very large screens, this has the effect of  taking up the whole screen and pushing content below the fold.

To demonstrate, load the webpage on a non-fullscreen window. Extend/contract the length of the page and ovserve the movie area change in size.

Suggest to change to fixed size or cap maximum height.

**Comment by RichardWild001** [comment]
_Suggest to change to fixed size or cap maximum height._

Sounds good to me.
